<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bardie.Contracts" Version="0.1.0" />
    <PackageVersion Include="Bardie.Module.Channel" Version="0.1.0" />
    <PackageVersion Include="Bardie.Module.Hosting" Version="0.1.0" />
    <PackageVersion Include="Bardie.Module.Auth" Version="0.1.0" />

    <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0" />

    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="10.0.0" />
  </ItemGroup>
</Project>
