<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bardie.Contracts" Version="0.1.0" />
    <PackageVersion Include="Bardie.Module.Channel" Version="0.1.0" />

    <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0" />

    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="10.0.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageVersion Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.14.0" />

    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.17.0-beta.1" />
  </ItemGroup>
</Project>
